### ISSUE TITLE
Implement download progress bar of model

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models-unity#5]
Display download progress using text or slider

**Comment by kyakuno** [comment]
Implement here.
https://github.com/axinc-ai/ailia-models-unity/blob/master/Assets/AXIP/AILIA-MODELS/common/Scripts/AiliaDownload.cs

**Comment by ri-shinpo** [comment]
sliderの場合では、ちゃんとしたUISilderがいいですか？それともUnityの標準Editor機能のProgressBarでもよろしいですか？
![image](https://user-images.githubusercontent.com/63228566/81383841-b5fc3180-914b-11ea-978f-83b61f67e0a9.png)

**Comment by ri-shinpo** [comment]
AiliaDownloadについて、Unityの`WWW`機能は2018.3から非推奨になったので、`UnityWebRequest`に変えようと思っています。

**Comment by kyakuno** [comment]
UnityWebRequestへの変更、よろしくお願いします。sliderはUnity標準のsliderで問題ないですが、アプリとして出力した場合にも動作する必要があるため、Editorではなく、Runtimeでも使用できるuGUIのsliderを使用してください。

**Comment by ri-shinpo** [comment]
uGUI用の既存のSliderBarアセットは仕様はありますか？

**Comment by kyakuno** [comment]
特にアセットはありませんので、フラットUIな見た目になるように単色の画像などをご利用ください。

**Comment by ri-shinpo** [comment]
AiliaDownloadにUIアセットのrefを保持したいため、下記の画像のようにAiliaDownloaderを作ろうかと思います。そしてダウンロード用のURLをまとめて定数化したいと思います。
![Annotation 2020-05-11 142738](https://user-images.githubusercontent.com/63228566/81526799-a2dba280-9393-11ea-9bae-4caab8044164.png)
![Annotation 2020-05-11 141821](https://user-images.githubusercontent.com/63228566/81526803-a5d69300-9393-11ea-8419-34334d13967d.png)
